### PR TITLE
[14.0] [FIX] show board service prices according to board service configuration (show_detail_report)

### PR DESCRIPTION
**Pull request by miguelpadin**
<ins>**BUG**</ins>: When a board service was configured to show included in the price of the reservation_line, the unit price was being miscalculated @ customer portal report.

_________________

<ins>**BEFORE FIX**</ins>:

https://user-images.githubusercontent.com/6873385/125443242-ca201571-8997-42b3-b5db-fe49ac86e50c.mp4

### CODE REVIEW

**Comment by miguelpadin** [comment]
This is the behavior before applying this change

https://user-images.githubusercontent.com/6873385/125411662-0ccde32d-55d5-4553-9b16-1a034f9cd32f.mp4

**Comment by miguelpadin** [comment]
<ins>**AFTER FIX**</ins>:

https://user-images.githubusercontent.com/6873385/125443388-ea845b6a-46d9-4807-9552-84d5a9020dc7.mp4

**Comment by miguelpadin** [comment]
@DarioLodeiros @eantones @OsoTranquilo @saralb9 @braisab

**Comment by DarioLodeiros** [comment]
Continue in https://github.com/OCA/pms/pull/64

**Pull request closed without merging**
