### PR TITLE
[14.0] [IMP] pms_l10n_es add traveller report

### PR DESCRIPTION
**Pull request by miguelpadin**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
Shouldn't this type of module be in OCA/l10n-spain ?

**Comment by rvalyi** [comment]
I agree with @marcelsavegnago, this seems strange to have it here. @pedrobaeza what's your take on this?

**Comment by pedrobaeza** [comment]
Well, indeed seems a bit transversal, but putting it on Spanish localization would mean that the CI needs to install the pms stack there, so it's a bit overkilling.

**Comment by marcelsavegnago** [comment]
> Well, indeed seems a bit transversal, but putting it on Spanish localization would mean that the CI needs to install the pms stack there, so it's a bit overkilling.

@pedrobaeza I see... but if it were, for example, the fieldservice_isp_account module for Brazil. Would we do the localization development within the fieldservice project?

**Comment by marcelsavegnago** [comment]
And if we have something in the PMS to develop the localization for Brazil, wouldn't we be overloading the PMS CI or field-service as mentioned in the previous example? it seems to me that it sets a precedent for the localized module to be developed inside other projects... I don't know if it seems the most suitable way.

**Comment by rvalyi** [comment]
I should say I tend to share the same view as @marcelsavegnago: I feel it wouldn't scale and the "precedent" thing isn't to be taken lightly.
Disclaimer I don't know the pms repo specificities.

**Comment by pedrobaeza** [comment]
Take into account that this is not a localization thing, but a PMS requirement only for Spain... The difference is that there's no dependency on anything on OCA/l10n-spain, but only a module that doesn't serve for the rest of countries, as it's the traveller register through the Spanish Police web service.

And thus it's something specific for the country, yes, but very decoupled from the rest of the Spanish localization and coupled with PMS. But well, there's no black or white here. I let the maintainers to decide.

**Comment by DarioLodeiros** [comment]
We have also thought about the possibility of taking it to the Spanish location, but in line with what Pedro has said, we have thought it more appropriate to put it in this repository because it is deeply linked to it. It is also an alpha development and I think it makes it easier for us to have it here for the moment, without putting noise in more mature repositories such as the localization one.
If we see that it is better to take it to location, now or in the future, without a problem on my part.

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
