### PR TITLE
[IMP]14.0 pms wizard several partners

### PR DESCRIPTION
**Pull request by braisab**

### CODE REVIEW

**Comment by braisab** [comment]
Reservation possible customers:
https://user-images.githubusercontent.com/38132068/132873617-ad5664b0-0b5c-4be7-92db-ce0517045cf2.mp4

Folio possible customers:
https://user-images.githubusercontent.com/38132068/132873712-ca82d85a-1502-424f-b4a9-3fb7d331cfd5.mp4

Checkin partner possible customers
https://user-images.githubusercontent.com/38132068/132873795-6508db20-e8ac-4265-b51c-0ba8ce830c9e.mp4

**Review by DarioLodeiros — DISMISSED** [review]

**Comment by braisab** [comment]
Resolved conflicts and fixed autocompletion of partner_name field when partner_id is added from the wizard

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
