### PR TITLE
[FIX] pms_l10n_es: add dependency to l10n_es_aeat_partner_identification

### PR DESCRIPTION
**Pull request by robinkeunen**
Adds the module while the matching PR is not merged https://github.com/OCA/l10n-spain/pull/2520

### CODE REVIEW

**Comment by robinkeunen** [comment]
I fixed the module dependency issue to run the tests. There are a lot of broken tests, before I dive head first, do you have advice on where to start ?

```
 Module pms: 10 failures, 41 errors of 365 tests 
```

Congrats on the extended test suite 💪

**Comment by robinkeunen** [comment]
I moved the setup of test data setup from `setUp` to `setUpClass`. The tests with OCB went from 11:15m to 6:50 minutes. \o/

**Comment by DarioLodeiros** [comment]
Our plan is to settle v14 in the next few months and then migrate to v16 and take advantage of this to refactor the pms module, which has grown too much.
The tests define flows that unfortunately have been redefined without being updated in the definition of tests, some are redundant, others are no longer in line with "how it should work"... if you give me until next week I'll check the status of the tests and tell you I propose a roadmap to update them between the two. If you agree, we merge this PR and make new PRs based on it to complete the tests, what do you think?

Thanks for the collaboration!

**Comment by robinkeunen** [comment]
Yes, that's what I figured out when looking at document_type in folios. I agree with merging this PR as is then fixing the rest separatly, it will be clearer.

What's your plan for the refactor ? Something like 

1. fix tests
2. split pms in smaller modules
3. migrate to 16 ?

I would advise against splitting while migrating because it will make it hard later to maintain 14.0 and 16.0 in parallel, the codebase will be too different. 

It is also harder to spot errors if doing both at the same time.

We've done extensive refactoring on [coopiteasy/obeesdoo](https://github.com/beescoop/Obeesdoo) last year, we mainly renamed and split modules. we're available if you want to have a chat about it.

Waiting for your inputs 👌

**Comment by DarioLodeiros** [comment]
I was thinking of split pms for v16, not v14, but your proposal doesn't seem bad to me.
I can first make a proposal to recover the tests, and some changes that we have pending to stabilize the module, and once this is done, we analyze the pms split and the migration to v16, is that okay with you?

**Comment by robinkeunen** [comment]
Fine with me. @carmenbianca will start work on this on the 17th of July. It'd be great to work on a _greenable_ CI by then. Do you think that could be possible ?

I myself will be back on this in August.

**Comment by robinkeunen** [comment]
Hi @DarioLodeiros , can you merge this PR so we can work together on making the CI greener ?

**Comment by robinkeunen** [comment]
Hi @DarioLodeiros , can you merge this PR so we can work together on making the CI greener ?

**Pull request merged**
