### PR TITLE
[14.0] make precommit green again

### PR DESCRIPTION
**Pull request by robinkeunen**
This is an attempt at fixing precommit. The first commit gathers trivial changes 

- [ ] f6dd3ba761f34bed890f286c8643534c3f8efca4 silences `redundant-modulename-xml` : it looks like the targeted xml element could be directly included into the element it overloads but it feels like the developper had a reason to code it that way
- [x] 8a42abd7a13a7aa372913cef890a72dd533bc184 silences `incoherent-interpreter-exec-perm` : I as not sure about the correct way to fix that => Carmen fixed it
- [x] ~~bf05fd3f3fcce089a938395b4366a24afb43f3fc is wip : I'm not competent enough in js to fix the warnings~~
- [ ] removed eslint, submit https://github.com/coopiteasy/pms/pull/1 on pms once this PR is merged

### CODE REVIEW

**Comment by carmenbianca** [comment]
@robinkeunen I changed the get-pip.py incoherent-interpreter-exec-perm by setting `chmod +x` on that file. It either expects both executive permissions AND a shebang, or neither, but not a mix of both. This is poorly documented.

I've also bumped the template to get rid of some errors.

It doesn't seem to me like you've suppressed all the eslint errors. Depending on the maintainers, I think you can just disable eslint and open an issue with a reminder to re-enable it.

**Comment by robinkeunen** [comment]
I did not touch js indeed. Let's see what Dario thinks about muting eslint.

**Comment by robinkeunen** [comment]
Hi @DarioLodeiros , this PR makes pre-commit green with a combination of trivial fixes to some errors, silencing others and adapting the config for eslint.

Fo you think it would be merged ?

**Comment by robinkeunen** [comment]
@DarioLodeiros I rebased and fixed the commits.

**Comment by robinkeunen** [comment]
@miguelpadin @carmenbianca @voltrans-it-johan can you give me you POV on this PRs and [my other PRs on pms](https://github.com/OCA/pms/pulls/robinkeunen) ?

**Review by carmenbianca — APPROVED** [review]

**Review by DarioLodeiros — APPROVED** [review]

**Comment by DarioLodeiros** [comment]
@robinkeunen can you do a rebase 14 in this branch?

**Comment by robinkeunen** [comment]
@DarioLodeiros done 👍

**Comment by bosd** [comment]
What is the status of this one?

**Comment by robinkeunen** [comment]
It was ready for me. @DarioLodeiros ?

**Comment by bosd** [comment]
Who has the super powers here to merge?

**Comment by robinkeunen** [comment]
further fixes there : https://github.com/OCA/pms/pull/243

**Pull request merged**
