### PR TITLE
[14.0] ocabot update dotfiles  and fix precommit

### PR DESCRIPTION
**Pull request by robinkeunen**
superseeds https://github.com/OCA/pms/pull/241

### CODE REVIEW

**Comment by robinkeunen** [comment]
@bosd @DarioLodeiros

**Comment by bosd** [comment]
Looks like a standard copier update of the repo :)
Please fix the pre-commit.

You might want to enable wkhtmltopdf as it seems that module `pms_l10n_es` is generating reports.

**Comment by robinkeunen** [comment]
@bosd that should be better

**Review by bosd — APPROVED** [review]
Apprvoing, as this is supposed to fix ci builds.

**Comment by bosd** [comment]
@DarioLodeiros Are you a maintainer here? Can you merge?

**Review by DarioLodeiros — APPROVED** [review]

**Pull request merged**
